from dotenv import dotenv_values

CONFIG = dotenv_values('.env')

GITHUB_TOKEN = CONFIG['GITHUB_TOKEN']
REPO_OWNER = CONFIG['REPO_OWNER']
APPROVAL_USERS = CONFIG['APPROVAL_USERS'].split(',')
REPO = CONFIG['REPO']
INTERVAL_IN_SECONDS = int(CONFIG.get('INTERVAL_IN_SECONDS', 15))
APPROVALS_REQUIRED = int(CONFIG.get('APPROVALS_REQUIRED', 1))
TITLE_REGEX = CONFIG.get('TITLE_REGEX', '.*')